In [1]:
import pandas as pd
df = pd.read_csv("index_2.csv")

In [2]:
df.head()

         date             datetime cash_type  money            coffee_name
0  2025-02-08  2025-02-08 14:26:04      cash   15.0                    Tea
1  2025-02-08  2025-02-08 14:28:26      cash   15.0                    Tea
2  2025-02-08  2025-02-08 14:33:04      card   20.0               Espresso
3  2025-02-08  2025-02-08 15:51:04      card   30.0  Chocolate with coffee
4  2025-02-08  2025-02-08 16:35:01      cash   27.0    Chocolate with milk

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         262 non-null    object
 1   datetime     262 non-null    object
 2   cash_type    262 non-null    object
 3   money        262 non-null    float64
 4   coffee_name  262 non-null    object
dtypes: float64(1), object(4)
memory usage: 10.4+ KB

In [4]:
df.isnull().sum()

date           0
datetime       0
cash_type      0
money          0
coffee_name    0
dtype: int64

In [5]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [6]:
df.describe()

            money
count  260.000000
mean    26.307692
std      4.265053
min     15.000000
25%     25.000000
50%     27.000000
75%     29.000000
max     33.000000

In [7]:
df.columns

Index(['date', 'datetime', 'cash_type', 'money', 'coffee_name'], dtype='object')

In [14]:
df.tail()

,date,datetime,cash_type,money,coffee_name
257,2025-03-23,2025-03-23 14:55:46,cash,30.0,Cappuccino
258,2025-03-23,2025-03-23 15:15:36,card,25.0,Irish whiskey
259,2025-03-23,2025-03-23 17:59:25,card,28.0,Super chocolate
260,2025-03-23,2025-03-23 18:01:33,card,28.0,Vanilla with Irish whiskey
261,2025-03-23,2025-03-23 21:23:11,card,29.0,Coffee with Irish whiskey

In [15]:
df["money"].mean()

26.307692307692307

In [16]:
df["money"].sum()

6840.0

In [17]:
df.count()

date           260
datetime       260
cash_type      260
money          260
coffee_name    260
dtype: int64

In [18]:
df.isnull().sum()

date           0
datetime       0
cash_type      0
money          0
coffee_name    0
dtype: int64

In [19]:
df.isnull().values.any()

False